#!/usr/bin/env bash
set -e

scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
doxDir=$scriptDir/../../generated/dox
xmlDir=$doxDir/xml
apiDir=$scriptDir/../../docs/api

# Generate xml from the source code
mkdir -p $doxDir
[ -d "$xmlDir" ] && rm -r $xmlDir
doxygen tools/gen-dox/Doxyfile

# Generate markdown from the xml
[ -d "$apiDir" ] && rm -r $apiDir
mkdir -p $apiDir
python3 $scriptDir/xmlparser.py
