# Build the firmware with this app linked in.
#
#   make cf21bl_defconfig && make
#
# See README.md for building it together with the TDoA capture config fragment,
# which is the normal way to use it.
CRAZYFLIE_BASE := ../..
OOT_CONFIG := $(PWD)/app-config
include $(CRAZYFLIE_BASE)/tools/make/oot.mk
