#!/usr/bin/env bash
set -e

scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
rootDir=$scriptDir/../..

# Generate the log and parameter documentation from the source code
python3 $rootDir/tools/logparam-doc/logparam_doc.py --root $rootDir src $rootDir/docs/api
