obj-y += attitude_pid_controller.o
obj-y += controller_indi.o
obj-y += controller_mellinger.o
obj-y += controller.o
obj-y += controller_pid.o
obj-y += controller_brescianini.o
obj-y += controller_single_ppid.o
obj-y += controller_omni_att.o
obj-y += controller_Gimbal2D.o
obj-y += position_controller_indi.o
obj-y += position_controller_pid.o

