VPATH += src/
PROJ_OBJ += uwbOlsr.o
PROJ_OBJ += olsrAlgo.o
PROJ_OBJ += olsrStruct.o
PROJ_OBJ += adhocdeck.o
PROJ_OBJ += adHocApp.o
PROJ_OBJ += endToEnd.o
PROJ_OBJ += adHocOnBoardSim.o

INCLUDES += -Iinterface/
CRAZYFLIE_BASE=../../../../../
include $(CRAZYFLIE_BASE)/Makefile