obj-y += estimator_complementary.o
obj-$(CONFIG_ESTIMATOR_KALMAN_ENABLE) += estimator_kalman.o
obj-$(CONFIG_ESTIMATOR_UKF_ENABLE) += estimator_ukf.o
obj-y += estimator.o
obj-y += position_estimator_altitude.o
