
# enable app support
APP=1
APP_STACKSIZE=300

VPATH += src/
PROJ_OBJ += app_main.o app_ledseq.o app_high_level_commander.o app_lighthouse.o app_memory_mapping.o app_loco.o

CRAZYFLIE_BASE=../..
include $(CRAZYFLIE_BASE)/Makefile
