/*
 * This file was autogenerated by OSQP-Python on August 29, 2022 at 18:00:54.
 * 
 * This file contains the workspace variables needed by OSQP.
 */

#include "types.h"
#include "qdldl_interface.h"

// Define data structure
static c_int Pdata_i[6] = {
0,
1,
2,
3,
4,
5,
};
static c_int Pdata_p[7] = {
0,
1,
2,
3,
4,
5,
6,
};
static c_float Pdata_x[6] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static csc Pdata = {6, 6, 6, Pdata_p, Pdata_i, Pdata_x, -1};
static c_int Adata_i[12] = {
0,
3,
1,
3,
2,
3,
0,
4,
1,
4,
2,
4,
};
static c_int Adata_p[7] = {
0,
2,
4,
6,
8,
10,
12,
};
static c_float Adata_x[12] = {
(c_float)1.00000000000000000000,
(c_float)0.17594719965875199597,
(c_float)1.00000000000000000000,
(c_float)-0.99784609866265083777,
(c_float)1.00000000000000000000,
(c_float)0.36318629375584099428,
(c_float)1.00000000000000000000,
(c_float)-0.17594719965875199597,
(c_float)1.00000000000000000000,
(c_float)0.99784609866265083777,
(c_float)1.00000000000000000000,
(c_float)0.36318629375584099428,
};
static csc Adata = {12, 5, 6, Adata_p, Adata_i, Adata_x, -1};
static c_float qdata[6] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
static c_float ldata[5] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.09810000000000000664,
(c_float)-9077669334311812014674932662272.00000000000000000000,
(c_float)-9077669334311812014674932662272.00000000000000000000,
};
static c_float udata[5] = {
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
(c_float)0.09810000000000000664,
(c_float)0.00000000000000000000,
(c_float)0.00000000000000000000,
};
static OSQPData data = {6, 5, &Pdata, &Adata, qdata, ldata, udata};

// Define settings structure
static OSQPSettings settings = {(c_float)0.10000000000000000555, (c_float)0.00000100000000000000, 10, 1, 0, (c_float)5.00000000000000000000, 4000, (c_float)0.00100000000000000002, (c_float)0.00100000000000000002, (c_float)0.00010000000000000000, (c_float)0.00010000000000000000, (c_float)1.00000000000000000000, (enum linsys_solver_type) LINSYS_SOLVER, 0, 25, 1, };
 
// Define scaling structure
static c_float Dscaling[6] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static c_float Dinvscaling[6] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
};
static c_float Escaling[5] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)9.07766933431181222147,
(c_float)9.07766933431181222147,
};
static c_float Einvscaling[5] = {
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)0.11016043470763975387,
(c_float)0.11016043470763975387,
};
static OSQPScaling scaling = {(c_float)1.00000000000000000000, Dscaling, Escaling, (c_float)1.00000000000000000000, Dinvscaling, Einvscaling};

// Define linsys_solver structure
static c_int linsys_solver_L_i[19] = {
1,
2,
2,
9,
6,
9,
4,
5,
5,
9,
6,
9,
7,
9,
9,
10,
9,
10,
10,
};
static c_int linsys_solver_L_p[12] = {
0,
2,
4,
6,
8,
10,
12,
14,
16,
18,
19,
19,
};
static c_float linsys_solver_L_x[19] = {
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)0.99009900009802975784,
(c_float)0.00359590386296967457,
(c_float)0.18249641377239117501,
(c_float)-0.18068951679752082162,
(c_float)-100.00000000000000000000,
(c_float)-100.00000000000000000000,
(c_float)0.99009900009802975784,
(c_float)0.00987966424537610466,
(c_float)-0.50140475462195688294,
(c_float)-0.49644034619559745947,
(c_float)-0.01665125175826622991,
(c_float)0.04067031064237439791,
(c_float)-0.00713491667311220556,
(c_float)0.99707782302652947504,
(c_float)-0.17594702371172829536,
(c_float)0.99999900000100006014,
(c_float)-0.01730430965950979436,
};
static csc linsys_solver_L = {19, 11, 11, linsys_solver_L_p, linsys_solver_L_i, linsys_solver_L_x, -1};
static c_float linsys_solver_Dinv[11] = {
(c_float)-100.00000000000000000000,
(c_float)0.00990099000098029758,
(c_float)0.50248706217718097644,
(c_float)-100.00000000000000000000,
(c_float)0.00990099000098029758,
(c_float)0.50248706217718097644,
(c_float)-0.09463777650659506435,
(c_float)0.99707782302652947504,
(c_float)0.99999900000100006014,
(c_float)-0.09451674820102912156,
(c_float)-0.49902472692344140848,
};
static c_int linsys_solver_P[11] = {
8,
5,
2,
7,
4,
1,
9,
0,
3,
10,
6,
};
static c_float linsys_solver_bp[11];
static c_float linsys_solver_sol[11];
static c_float linsys_solver_rho_inv_vec[5] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int linsys_solver_Pdiag_idx[6] = {
0,
1,
2,
3,
4,
5,
};
static c_int linsys_solver_KKT_i[23] = {
0,
1,
0,
2,
0,
3,
4,
3,
5,
3,
5,
2,
6,
7,
6,
8,
8,
4,
1,
9,
7,
8,
10,
};
static c_int linsys_solver_KKT_p[12] = {
0,
1,
3,
5,
6,
8,
10,
13,
15,
16,
20,
23,
};
static c_float linsys_solver_KKT_x[23] = {
(c_float)-0.01000000000000000021,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)-0.01000000000000000021,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)1.00000000000000000000,
(c_float)-0.99784609866265083777,
(c_float)0.36318629375584099428,
(c_float)-10.00000000000000000000,
(c_float)1.00000099999999991773,
(c_float)0.17594719965875199597,
(c_float)1.00000099999999991773,
(c_float)-0.17594719965875199597,
(c_float)0.99784609866265083777,
(c_float)0.36318629375584099428,
(c_float)-10.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)1.00000000000000000000,
(c_float)-0.01000000000000000021,
};
static csc linsys_solver_KKT = {23, 11, 11, linsys_solver_KKT_p, linsys_solver_KKT_i, linsys_solver_KKT_x, -1};
static c_int linsys_solver_PtoKKT[6] = {
13,
8,
3,
15,
6,
1,
};
static c_int linsys_solver_AtoKKT[12] = {
20,
14,
9,
10,
4,
11,
21,
16,
7,
17,
2,
18,
};
static c_int linsys_solver_rhotoKKT[5] = {
22,
5,
0,
12,
19,
};
static QDLDL_float linsys_solver_D[11] = {
0,
101,
1,
0,
101,
1,
-10,
1,
1,
-10,
-2,
};
static QDLDL_int linsys_solver_etree[11] = {
1,
2,
6,
4,
5,
6,
7,
9,
9,
10,
-1,
};
static QDLDL_int linsys_solver_Lnz[11] = {
2,
2,
2,
2,
2,
2,
2,
2,
2,
1,
0,
};
static QDLDL_int   linsys_solver_iwork[33];
static QDLDL_bool  linsys_solver_bwork[11];
static QDLDL_float linsys_solver_fwork[11];
static qdldl_solver linsys_solver = {QDLDL_SOLVER, &solve_linsys_qdldl, &update_linsys_solver_matrices_qdldl, &update_linsys_solver_rho_vec_qdldl, &linsys_solver_L, linsys_solver_Dinv, linsys_solver_P, linsys_solver_bp, linsys_solver_sol, linsys_solver_rho_inv_vec, (c_float)0.00000100000000000000, 6, 5, linsys_solver_Pdiag_idx, 6, &linsys_solver_KKT, linsys_solver_PtoKKT, linsys_solver_AtoKKT, linsys_solver_rhotoKKT, linsys_solver_D, linsys_solver_etree, linsys_solver_Lnz, linsys_solver_iwork, linsys_solver_bwork, linsys_solver_fwork, };

// Define solution
static c_float xsolution[6];
static c_float ysolution[5];

static OSQPSolution solution = {xsolution, ysolution};

// Define info
static OSQPInfo info = {0, "Unsolved", OSQP_UNSOLVED, 0.0, 0.0, 0.0};

// Define workspace
static c_float work_rho_vec[5] = {
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)100.00000000000000000000,
(c_float)0.10000000000000000555,
(c_float)0.10000000000000000555,
};
static c_float work_rho_inv_vec[5] = {
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)0.01000000000000000021,
(c_float)10.00000000000000000000,
(c_float)10.00000000000000000000,
};
static c_int work_constr_type[5] = {
1,
1,
1,
0,
0,
};
static c_float work_x[6];
static c_float work_y[5];
static c_float work_z[5];
static c_float work_xz_tilde[11];
static c_float work_x_prev[6];
static c_float work_z_prev[5];
static c_float work_Ax[5];
static c_float work_Px[6];
static c_float work_Aty[6];
static c_float work_delta_y[5];
static c_float work_Atdelta_y[6];
static c_float work_delta_x[6];
static c_float work_Pdelta_x[6];
static c_float work_Adelta_x[5];
static c_float work_D_temp[6];
static c_float work_D_temp_A[6];
static c_float work_E_temp[5];

OSQPWorkspace workspace_2uav_2hp = {
&data, (LinSysSolver *)&linsys_solver,
work_rho_vec, work_rho_inv_vec,
work_constr_type,
work_x, work_y, work_z, work_xz_tilde,
work_x_prev, work_z_prev,
work_Ax, work_Px, work_Aty,
work_delta_y, work_Atdelta_y,
work_delta_x, work_Pdelta_x, work_Adelta_x,
work_D_temp, work_D_temp_A, work_E_temp,
&settings, &scaling, &solution, &info};

