ifeq ($(CONFIG_PLATFORM_SIM),y)
# Simmyflie Phase 3 (Communication): the UDP CRTP link. Phase 4.0
# (Foundation HAL stubs) adds buzzer.o (already fully portable -- reused
# unmodified, no _sim.c needed), ledseq_sim.o, storage_sim.o, and
# usec_time_sim.o. Phase 4.2 (Platform) adds syslink_sim.o, a no-op stub for
# platformservice.c's setContinuousWave command -- real syslink.c talks to
# the NRF companion chip, which doesn't exist in sim (see syslink_sim.c).
# The rest of this tree (sensors, radio, USB, ...) is Phase 5's job.
obj-y += buzzer.o
obj-y += ledseq_sim.o
obj-y += storage_sim.o
obj-y += syslink_sim.o
obj-y += udplink_sim.o
obj-y += usec_time_sim.o
else
obj-y += amg8833.o
obj-y += buzzer.o
obj-y += freeRTOSdebug.o
obj-y += ledseq.o
obj-y += ow_syslink.o
obj-y += pca9555.o
obj-y += pca95x4.o
obj-y += pm_stm32f4.o
obj-y += proximity.o
obj-y += radiolink.o
obj-$(CONFIG_SENSORS_BMI088_BMP3XX) += sensors_bmi088_bmp3xx.o
obj-$(CONFIG_SENSORS_BMI088_I2C) += sensors_bmi088_i2c.o
obj-$(CONFIG_SENSORS_BMI088_SPI) += sensors_bmi088_spi.o
obj-$(CONFIG_SENSORS_BOSCH) += sensors_bosch.o
obj-$(CONFIG_SENSORS_MPU9250_LPS25H) += sensors_mpu9250_lps25h.o
obj-y += sensors.o
obj-y += storage.o
obj-y += syslink.o
obj-y += usb_bsp.o
obj-y += usbd_desc.o
obj-y += usblink.o
obj-y += usb.o
obj-y += usec_time.o
endif
