
obj-y += octoMap.o
obj-y += octoNode.o
obj-y += octoTree.o
obj-y += octoNodeSet.o
obj-y += rrtConnect.o
obj-y += circularQueue.o
obj-y += coordinateQueue.o
obj-y += auxiliary_tool.o
obj-y += control_tool.o
obj-y += communicate.o
obj-y += autoflyMainMul.o