ifeq ($(CONFIG_PLATFORM_SIM),y)
# Simmyflie Phase 4.0 (Foundation HAL stubs): just enough of this tree's
# public API to unblock system.c's init chain -- adc_sim.o (adcInit()),
# i2cdev_sim.o (i2cdevInit()), led_sim.o (led.h), watchdog_sim.o
# (watchdogNormalStartTest()). The rest of this tree (real sensor/motor
# drivers) is Phase 5's job.
obj-y += adc_sim.o
obj-y += i2cdev_sim.o
obj-y += led_sim.o
obj-y += watchdog_sim.o
else
obj-y += ak8963.o
obj-y += cppm.o
obj-y += eeprom.o
obj-y += exti.o
obj-y += fatfs_sd.o
obj-y += i2cdev.o
obj-y += i2c_drv.o
obj-y += led.o
obj-y += lh_bootloader.o
obj-y += lps25h.o
obj-y += maxsonar.o
obj-y += motors.o
obj-y += mpu6050.o
obj-y += mpu6500.o
obj-y += ms5611.o
obj-y += nvic.o
obj-y += pca9685.o
obj-y += piezo.o
obj-y += pmw3901.o
obj-y += swd.o
obj-y += uart1.o
obj-y += uart2.o
obj-y += uart_syslink.o
obj-y += vl53l0x.o
obj-y += vl53l1x.o
obj-y += watchdog.o
obj-y += ws2812_cf2.o
endif
