ifeq ($(CONFIG_PLATFORM_SIM),y)
# Simmyflie Phase 3 (Communication): the ASSERT()/DEBUG_PRINT backend
# crtp.c/queuemonitor.c need (see cfassert_sim.c). Phase 4.0 (Foundation
# HAL stubs) adds configblock_sim.o. Phase 4.1 (Console) adds debug.o/
# eprintf.o -- both already fully hardware-free, so DEBUG_PRINT can route
# through the new real console.c's consolePrintf() unmodified. The rest of
# this tree (CRC, filters, ...) isn't needed yet.
obj-y += cfassert_sim.o
obj-y += configblock_sim.o
obj-y += debug.o
obj-y += eprintf.o
else
obj-y += cfassert.o
obj-y += clockCorrectionEngine.o
obj-y += configblockeeprom.o
obj-y += cpuid.o
obj-y += crc32.o
obj-y += debug.o
obj-y += eprintf.o
obj-y += buf2buf.o

obj-y += filter.o
obj-y += FreeRTOS-openocd.o

obj-y += num.o
obj-y += rateSupervisor.o
obj-y += sleepus.o
obj-y += statsCnt.o

### Sub directories
obj-y += kve/
obj-y += lighthouse/
obj-y += tdoa/


### Implementations for abort(), malloc() and free(), needed to interact with apps written in C++
obj-y += abort.o
obj-y += malloc.o
obj-y += pid.o

### Rules for handling generated version.c
obj-y += version.o
version-objs := version_gen.o
src/utils/src/version_gen.c: src/utils/src/version.vtpl FORCE
	 $(PYTHON) $(srctree)/tools/make/versionTemplate.py --crazyflie-base $(srctree) $< $@
endif
