# This work flow checks out the repo and reads the list of release targets from
# the build_targetst.json file.

# The list of targets is available in needs.read_targets_from_file.outputs.platforms as a json dictionary, use it
# in matrix like this: ${{fromJson(needs.read_targets_from_file.outputs.platforms)}}

name: Read build targets

on:
  workflow_call:
    outputs:
      platforms:
        description: "'platform' is set to the list of targets"
        value: ${{ jobs.read_targets_from_file.outputs.platforms }}

permissions:
  contents: read

jobs:
  read_targets_from_file:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.read-build-target-from-file.outputs.platforms }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: false

    - id: read-build-target-from-file
      run: |
        content=`cat ./build_targets.json`
        # the following lines are required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of handling for multi line json
        echo "::set-output name=platforms::$content"
