# Release jobs

name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  read_targets_from_file:
    uses: bitcraze/workflows/.github/workflows/read_build_targets.yml@41b8cc3c616fd6fad685c3411f21f72646333b19
    with:
      target_file: './build_targets.json'

  release:
    permissions:
      contents: write  # for softprops/action-gh-release to create a release
    name: Create Release on Github
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@e598afbe1493e6b1bafb1f389cabb956eab91231 # v3.0.3
      with:
        tag_name: ${{ github.ref }}
        name: ${{ github.ref }}
        draft: true
        prerelease: true

  upload:
    permissions:
      contents: write  # for softprops/action-gh-release to upload release assets
    name: Upload Binaries to release
    needs: [release, read_targets_from_file]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ${{fromJson(needs.read_targets_from_file.outputs.platforms)}}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: Build
      run: docker run --rm -v ${PWD}:/module bitcraze/builder bash -c "make ${{ matrix.platform }}_defconfig && ./tools/build/build PLATFORM=${{ matrix.platform }} UNIT_TEST_STYLE=min"

    - name: Get the version
      id: get_release_version
      env:
        GITHUB_REF : ${{ github.ref }}
      run: echo "release_version=$(echo "${GITHUB_REF/refs\/tags\//}" | tr '/' '-')" >> $GITHUB_OUTPUT

    - name: Rename binary for upload
      run: |
        mkdir -p release_assets
        cp build/${{ matrix.platform }}.bin release_assets/${{ matrix.platform }}-${{ steps.get_release_version.outputs.release_version }}.bin

    - name: Upload ${{ matrix.platform }} bin
      uses: softprops/action-gh-release@e598afbe1493e6b1bafb1f389cabb956eab91231 # v3.0.3
      with:
        tag_name: ${{ github.ref }}
        draft: true
        prerelease: true
        files: release_assets/${{ matrix.platform }}-${{ steps.get_release_version.outputs.release_version }}.bin
